# Generated by Django 5.2.13 on 2026-04-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="learning_interests",
            field=models.TextField(
                blank=True,
                help_text="Comma separated interests such as Python, AI, design",
            ),
        ),
    ]
