# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


def backfill_payment_data(apps, schema_editor):
    Enrollment = apps.get_model('learning', 'Enrollment')
    for enrollment in Enrollment.objects.select_related('course').all():
        if enrollment.course.price and enrollment.course.price > 0:
            enrollment.payment_status = 'paid'
            enrollment.payment_method = 'upi'
            enrollment.paid_amount = enrollment.course.price
            if not enrollment.payment_reference:
                enrollment.payment_reference = f'LEGACY-{enrollment.id}'
            if enrollment.payment_at is None:
                enrollment.payment_at = enrollment.enrolled_at
        else:
            enrollment.payment_status = 'free'
            enrollment.paid_amount = 0
            enrollment.payment_method = ''
        enrollment.save(
            update_fields=[
                'payment_status',
                'payment_method',
                'paid_amount',
                'payment_reference',
                'payment_at',
                'updated_at',
            ]
        )


def reverse_backfill_payment_data(apps, schema_editor):
    Enrollment = apps.get_model('learning', 'Enrollment')
    Enrollment.objects.all().update(
        payment_status='free',
        payment_method='',
        paid_amount=0,
        payment_reference='',
        payment_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Credit / Debit Card'), ('net_banking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='free', max_length=20),
        ),
        migrations.RunPython(backfill_payment_data, reverse_backfill_payment_data),
    ]
