# Generated by Django 5.2.12 on 2026-03-31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_background_image'),
        ('learning', '0003_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit / Debit Card'), ('net_banking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_name', models.CharField(default='SmartLMS MockPay', max_length=50)),
                ('response_message', models.CharField(blank=True, max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_payments', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_payments', to='learning.enrollment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mock_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
