# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_backgrounds/'),
        ),
    ]
